name: bora_trocar
description: "A new Flutter project."
publish_to: 'none' # Remove esta linha se quiser publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # ✅ Pacote INTl ADICIONADO para formatação de data na NewAdPage
  intl: ^0.18.1 

  provider: ^6.0.0
  
  shared_preferences: ^2.1.0  # Adicionando o número de patch
  
  # Pacotes externos
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1  # pacote para abrir links externos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Exemplo de assets (descomente se usar)
  # assets:
  #   - images/
  
  # Exemplo de fontes (descomente se usar)
  # fonts:
  #   - family: Schyler
  #   # ...